-----
### 자원 정리
-----
1. CallException (/tcp/autoclosable)
```java
package network.tcp.autoclosable;

public class CallException extends Exception {
    public CallException(String message) {
        super(message);
    }
}
```
2. CloseException (/tcp/autoclosable)
```java
package network.tcp.autoclosable;

public class CloseException extends Exception {
    public CloseException(String message) {
        super(message);
    }
}
```

3. ResourceV1 (/tcp/autoclosable)
```java
package network.tcp.autoclosable;

public class ResourceV1 {
    private String name;

    public ResourceV1(String name) {
        this.name = name;
    }

    public void call() { // 호출
        System.out.println(name + " call");
    }

    public void callEx() throws CallException { // CallException
        System.out.println(name + " call Ex");
        throw new CallException(name + " ex");
    }

    public void close() { // 자원 정리
        System.out.println(name + " close");
    }

    public void closeEx() throws CloseException { // CloseException
        System.out.println(name + " closeEx");
        throw new CloseException(name + " ex");
    }
}
```

  - call() : 정상 로직 호출
  - callEx() : 비정상 로직 호출 (CallException을 던짐)
  - close() : 정상 종료
  - closeEx() : 비정상 종료 (CloseException을 던짐)

4. ResourceCloseMainV1
```java
package network.tcp.autoclosable;

public class ResourceCloseMainV1 {
    public static void main(String[] args) {
        try {
            logic();
        } catch (CallException e) {
            System.out.println("CallException 예외 처리");
            throw new RuntimeException(e);
        } catch (CloseException e) {
            System.out.println("CloseException 예외 처리");
            throw new RuntimeException(e);
        }
    }

    private static void logic() throws CallException, CloseException {
        ResourceV1 resource1 = new ResourceV1("resource1");
        ResourceV1 resource2 = new ResourceV1("resource2");

        resource1.call();
        resource2.callEx(); // CallException

        System.out.println("자원 정리"); // 호출 되지 않음
        resource2.closeEx(); // 자원 정리 단계에서 CloseException
        resource1.closeEx();
    }
}
```
  - 서로 관련된 자원은 나중에 생성한 자원을 먼저 정리해야 함
  - 예를 들어, resource1을 생성하고, resource1의 정보를 활용해서 resource2를 생성한다면, 닫을 때는 그 반대인 resource2를 먼저 닫고, 그 다음에 resource1을 닫아야 함
    + resource2 입장에서 resouce1의 정보를 아직 참고하고 있기 때문임
  - 이 예제에서는 두 자원이 서로 관련이 없기 때문에, 생성과 종료 순서가 크게 상관이 없지만, resource1의 정보를 기반으로 resource2를 생성한다고 가정

5. 실행 결과
```
resource1 call
resource2 call Ex
CallException 예외 처리
Exception in thread "main" java.lang.RuntimeException: network.tcp.autoclosable.CallException: resource2 ex
	at network.tcp.autoclosable.ResourceCloseMainV1.main(ResourceCloseMainV1.java:9)
Caused by: network.tcp.autoclosable.CallException: resource2 ex
	at network.tcp.autoclosable.ResourceV1.callEx(ResourceV1.java:16)
	at network.tcp.autoclosable.ResourceCloseMainV1.logic(ResourceCloseMainV1.java:21)
	at network.tcp.autoclosable.ResourceCloseMainV1.main(ResourceCloseMainV1.java:6)
```
  - callEx() 호출하면서 에외 발생
  - 예외 때문에 자원 정리 코드가 정상 호출되지 않음
  - 즉, 예외가 발생하면 자원 정리가 되지 않는 문제 발생
